### ISSUE TITLE
Development: Cloud Functions 

### ISSUE THREAD

**Issue by s3687636** [nguyenducminhtam/sepm-snapie#32]
- [x] for request image info: image-in, text-out
- [x] for request image from search keyword (text): text-in, image URL-out

**Comment by trungduong0103** [comment]
> * for request image info: image-in, text-out
> * for request image from search keyword (text): text-in, image URL-out

I'll work on this after I figure out how to set up a camera in react native. For request image, do you think it's better to get the result as something else rather than URL ? might make it faster to load the image. And how many images should we query ?

**Comment by trungduong0103** [comment]
Cloud Functions added:
- [x] Request image labels:
https://asia-northeast1-rmit-sepm.cloudfunctions.net/getImageLabels
request body: 
{
'image': base64 encoded string,
'rawResult': string,
'maxResults': number,
}

rawResult can be a string (preferably 'true'), if rawResult is added, the entire response object will be returned, otherwise, the return object will have the label and the confidence score of that label.
maxResults represents the maximum result returned.

- [x] Request image from search keyword:
https://asia-northeast1-rmit-sepm.cloudfunctions.net/searchImageByKeyword
request body: 
{
'keyword': string,
}
keyword represents the keyword that will be queried to unsplash. MAXIMUM 50 requests/hour for now.

**Comment by trungduong0103** [comment]
This should be closed right ? we have other issues for other cloud functions. @s3687636
